[package]
name = "solidtrace_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
# --- MOTOR VE SİSTEM ÇEKİRDEĞİ ---
tokio = { version = "1", features = ["full"] }
sysinfo = "0.29"
is_elevated = "0.1"
notify = "6.1.1"
sha2 = "0.10"
hex = "0.4"
once_cell = "1.18"
lazy_static = "1.4"
yara-x = "0.7"
dirs = "4.0"

# --- AĞ VE İLETİŞİM (Backend & Update) ---
reqwest = { version = "0.11", features = ["json", "rustls-tls"] } 
tokio-tungstenite = "0.20"
url = "2.4"
futures-util = "0.3"

# --- VERİ İŞLEME VE FORMAT ---
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

# --- SİSTEM ARAÇLARI ---
whoami = "1.4"
local-ip-address = "0.5"
walkdir = "2.3"
winreg = "0.52"